In [1]:
# Funciones Universales

In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [6]:
arreglo_radiantes = arreglo_grados * np.pi / 180
arreglo_radiantes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
np.sin(arreglo_radiantes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [8]:
np.cos(arreglo_radiantes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [9]:
np.tan(arreglo_radiantes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [11]:
numero_random = np.random.randint( #Se usa randint para enteros
    11 #Quiero que me traigas un numero entero desde [0 , 11[
)
numero_random

2

In [16]:
numero_random_negativo = np.random.randint(
    -9,
    2         # [-9, 2[
)
numero_random_negativo

-4

In [2]:
arreglo_random = np.random.randint(
    10,
    20,
    8             #Define los elementos del arreglo
)
arreglo_random

array([12, 13, 18, 17, 12, 12, 16, 13])

In [18]:
np.average(arreglo_random)

13.625

In [19]:
np.mean(arreglo_random)

13.625

In [20]:
np.median(arreglo_random)

13.5

In [21]:
np.std(arreglo_random)

2.7357585785299112

In [4]:
np.var(arreglo_random,axis = 0)

5.359375

In [5]:
arregloNumeros = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(arregloNumeros[-5:-2])

[5, 6, 7]
